export const SAMPLE_ORG_POLICY_TEXT = `POLICY:
The Organization ("Organization") is committed to fostering a culture of compliant and ethical conduct. Accordingly, the Organization maintains a system and processes for the investigation of any known or suspected violations of law, privacy, confidentiality, Organization policies and procedures, known or suspected fraud, waste and abuse or other acts involving non-compliance (collectively "Non-Compliance").

PURPOSE:
The purpose of this policy is to establish written policies and procedures designed to support compliance with various Federal and New York State ("State" or "NYS") laws and best practices pertaining to the investigation of compliance issues or violations.

Note: this policy is not intended to address audits and reviews performed as part of the Compliance Program auditing, monitoring and risk assessment processes.

SCOPE:
This policy governs the requirements outlined herein and applies to all Organization employees, affiliates, contractors, volunteers, students and trainees (collectively "Personnel") at all Organization owned, operated or affiliated facilities, entities and programs.

DEFINITIONS:
A. In Good Faith: Means reporting or participating with the honest and reasonable belief that at that time, non-compliance may have occurred.
B. Retaliation or Intimidation: Means an adverse action taken against an individual or entity as a direct result of that individual's participation in the Organization Compliance Program. Actions generally include but are not limited to the inappropriate discharge, suspension or demotion of an individual or any threatening, discriminatory or other adverse action taken against an individual or entity in the terms and conditions of such employment, contract or other affiliation with the Organization.
C. Whistleblower: Means Organization personnel or other individuals or entities that know or have reason to suspect non-compliance have occurred and who in good faith participates in the Organization Compliance Program and as described in this policy.
D. Non-Compliance: Means, for the purpose of this policy, issues or matters related to violations of the law or the Organization's Compliance Program and includes, without limitation: known or suspected misconduct, compliance or non-compliance issues; known or suspected violations of employee or patient privacy or confidentiality; known or suspected violations of any applicable law or regulation; known or suspected violations of the Organization's policies and procedures, the Organization Code of Conduct or the Organization Compliance Program; potential overpayments; related risks under self or external audit, review or investigation; performing or participating in internal or external investigations, reviews and audits; cooperating with or implementing remedial actions in response to noted compliance issues, deficiencies or failures; known or suspected fraud, waste or abuse; and situations covered under Labor Law §§ 740 and 741, including violations that create and/or present a substantial and specific danger to the public health or safety, or which constitute health care fraud, or situations where Personnel reasonably believe constitute improper quality of patient care.

RESPONSIBILITIES:
1. Compliance and Privacy Department: In collaboration with other departments, is responsible for ensuring that, in accordance with applicable law, the Organization complies with the statutory and regulatory requirements with respect to performing investigations or reviews of Non-Compliance and protecting Personnel and other individuals or entities from retaliation or intimidation, including participation in the development of policies and internal controls or systems designed to do such.
2. Personnel: Are responsible for performing their job functions in compliance with this policy. Failure to maintain such compliance may result in disciplinary action up to and including termination of employment, contract or other affiliation with the Organization.

PROCEDURES/GUIDELINES:

A. Investigation Authority and Related Processes
1. The Compliance and Privacy Department, exercising sound judgment on a case-by-case basis, shall have absolute discretion as to whether a query, report, problem, issue, concern, matter, complaint or request for guidance (collectively "Reports") of known or suspected Non-Compliance warrants an investigation or review.
2. The Compliance and Privacy Department, exercising sound judgment, shall have absolute discretion as to assigning a priority of the investigation or review of a Report of known or suspected Non-Compliance (e.g., patient care related matters or those which involve an imminent threat to Personnel or the public, will take priority).
3. Reports of Non-Compliance that are received, referred to, discovered or otherwise obtained by the Compliance and Privacy Department, at the discretion of the Compliance and Privacy Department, shall be assigned a case identification number and entered into the compliance reporting tracking system.
4. Generally, and unless an imminent threat or situation is identified, investigations shall commence within three (3) business days of any Report of known or suspected Non-Compliance. The Compliance and Privacy Department shall take the time necessary as it deems appropriate to thoroughly review or investigate any known or suspected Non-Compliance, however shall do so with the essence of time in mind while balancing the exercising of performing such with due diligence. Additionally, while there is no statute of limitation related to a Report of known or suspected Non-Compliance, the investigation shall take into account the applicability of the facts as well as the legal requirement for any external reporting or notice, both of which may bear weight on the substance or necessity of the investigation.
5. Although there is no requirement that all methods of communication to the Compliance and Privacy Department be confidential, the Compliance and Privacy Department must establish and maintain one (1) method of confidential communication that is available to all Personnel and other individuals and entities, for the submission of Reports of known or suspected Non-Compliance.
6. Unless otherwise required by applicable Federal or State law, all investigations shall be conducted with due diligence to determine whether there is credible evidence that a probable material commission of an act related to Non-Compliance has occurred.
7. The Compliance and Privacy Department is responsible for determining a plan of investigation prior to the start of the investigation or review. The plan may be revised as the investigation proceeds and may include, without limitation: identifying documents for review/creating a document request; identifying appropriate Personnel, entities or other individuals to be interviewed; developing questions to be asked during such interviews; determining notification methods to those being summoned for an interview; gathering and reviewing all potential applicable or appropriate documents (e.g., patient records, billing/claims records, training records, etc.); reviewing Organization policies and procedures; and defining sampling methodology, if applicable.
8. The Compliance and Privacy Department representative and/or others performing investigations or assisting with investigations or reviews under the purview of, have an affirmative obligation to protect the integrity of the investigatory process which includes, without limitation: maintaining a confidential process; taking appropriate measures to limit the likelihood of retaliation or intimidation of Personnel or other individuals or entities who are cooperating with an investigation; informing those participating in the investigation of the Organization's policy on Non-Retaliation or Intimidation; and proceeding with discretion, including being careful to protect the reputations and identities of those being investigated, to the extent reasonably possible under the circumstances.
9. Throughout the investigation or review of known or suspected Non-Compliance, the Compliance and Privacy Department reserves the right to independently and unilaterally: engage the services of independent outside legal counsel when deemed warranted; engage the assistance or services of other Organization departments or Personnel when deemed warranted; and notify any external regulatory or enforcement agency or entity, as may be required under Federal or State law, of any pending or ongoing investigations or the outcome of such investigation.
10. The Compliance and Privacy Department will determine whether it is necessary to disclose the findings of an investigation, elements related to an investigation or otherwise notify or report to an external entity (e.g., disclosure of identified overpayment, breach notice), as required under Federal, State law, guidance or contract, to such entities including without limitation: Centers for Medicare and Medicaid Services (CMS); U.S. Department of Health and Human Services Office of Inspector General (OIG); U.S. Department of Health and Human Services Office for Civil Rights (OCR); NYS Office of the Medicaid Inspector General (OMIG); NYS Office of Attorney General (AG); NYS Department of Health (DOH); NYS Office of Mental Health (OMH); NYS Education Department; NYS Office of Professional Medical Conduct (OPMC); U.S. Department of Justice (DOJ); Federal, State or local law enforcement; other Federal or State enforcement, Attorney General or Inspector General offices, as required under the law; external entities in partnership or contract with the Organization wherein the Organization may be legally or contractually required (e.g., Regional Health Information Network); and managed care organizations and other private payers.
11. The Compliance and Privacy Department will determine, as part of the findings related to an investigation, if certain actions are required to address any known or suspected Non-Compliance, assessing factors including: whether an overpayment has been identified that requires disclosure of and refunding to OMIG, OIG or private payers; whether it is necessary to perform a root cause analysis (RCA); whether mitigation or remediation requires intervention, training or education; whether the act necessitates supplementation to or changes in Organization internal controls to prevent recurrence; whether the matter requires follow-up including future reviews or audits; and whether revision or development of current Organization policies and procedures is required.

B. Individuals or Entities Participating in Compliance Investigations
1. Personnel and other individuals or entities associated with the Organization have an affirmative obligation to Report and/or participate, truthfully and In Good Faith, in the investigation or review of any known or suspected Non-Compliance.
2. The confidentiality of any individual who makes a Report, including the identity of any Whistleblower, shall be preserved to the extent possible unless required to be disclosed under Federal or State law. Notwithstanding, confidentiality must yield to other Organization values or concerns such as disclosure to law enforcement based on a public safety threat or to a regulatory or enforcement entity conducting an external investigation.
3. Personnel and other individuals who are part of an investigation shall be informed by the Compliance and Privacy Department that retaliation against or intimidation of any individual or entity who files a Report or otherwise cooperates in or assists with the investigation or review of known or suspected Non-Compliance is strictly prohibited, and that any individual who participates in or condones such action is subject to disciplinary action up to and including termination of employment, contract or other affiliation with the Organization.
4. The Compliance and Privacy Department representative conducting an investigation reserves the right to request the removal of any other individuals present at or involved in the investigation if the representative believes the integrity of the investigation may be at stake because of the presence or involvement of another individual.
5. Individuals or entities present at or involved in the investigation are generally not permitted the disclosure of any protected health information (PHI) or other confidential business information, unless it is deemed essential, necessary, or otherwise material to the investigation, by the Compliance and Privacy Department (e.g., Personnel who are union representatives, external individuals serving in the role of union representatives, representatives from external entities). In these situations, other individuals present may be asked to temporarily remove themselves.

C. Internal Reporting
1. The Compliance and Privacy Department will provide summary information of Reports of Non-Compliance and the subsequent review, investigation and outcome thereof, to both the internal Compliance Committee and to the Organization Board of Trustees, on a periodic basis, as identified in the Organization's Compliance Program.
2. Where requested, due to significant events related to Non-Compliance, the Compliance and Privacy Department reserves the right to seek consultation, advice or further intervention or involvement of the Board of Trustees.

D. Records and Documentation
1. The Compliance and Privacy Department shall maintain the following documentation and other records related to an investigation: documentation of the Non-Compliance that is the subject of the investigation and initial Report(s); documentation of the investigatory process used; copies of any interview notes, related statements and documents; copies of other key documents, photographs, messages or recordings; the results and outcome of the investigation, including, when applicable, a Summary Investigative Report; and copies of any disciplinary action and/or corrective measures taken as a result of the investigation or its outcome. All documents and other records shall be maintained within the compliance tracking system to the extent reasonably possible. Where a hard copy of a record is maintained elsewhere, the specific location of such must be documented in the compliance reporting tracking system.
2. The Compliance and Privacy Department shall routinely develop a Summary Investigative Report, at the conclusion or where otherwise warranted, including: nature of the problem; a list of all known facts; summary of investigative process; identification of any person(s), as appropriate and where warranted for disciplinary action, or process(es) which the Compliance and Privacy Department believes to have contributed deliberately or with reckless disregard or intentional indifference or otherwise toward the known or suspected Non-Compliance; findings, recommendations and actions taken; and, when necessary, and with the assistance of the Chief Financial Officer (CFO) or their designee, estimates of the nature and extent of any resulting overpayment, if any.
3. Records related to the investigation or review of any known or suspected Non-Compliance shall be maintained for a minimum of ten (10) years.

RELEVANT REFERENCES:
1. 18 NYCRR § 521-1.3 (current cite; formerly § 521.3, repealed and replaced effective 2022-12-28).
2. 45 CFR §§ 160.316 and 164.530.
3. NYS Labor Law §§ 740 and 741.
4. NYS GBS § 899-aa.
5. 42 USC §§ 1320a-7b(b) and 1395nn.
6. 31 USC §§ 3729-3733.
7. NYS Finance Law §§ 187-194.
8. NYS Penal Law §§ 176 and 177.
9. U.S. Department of Health and Human Services Office of Inspector General, "Publication of the OIG Compliance Program Guidance for Hospitals," 63 Fed. Reg. 35, 8987, 8994 (Feb. 23, 1998).
10. U.S. Department of Health and Human Services Office of Inspector General, "Supplemental Compliance Guidance for Hospitals," 70 Fed. Reg. 4858, 4875 (Jan. 31, 2005).`;
